---
collections:
  - name: kubernetes.core
    version: ">=5.0.0"
  - name: ansible.controller
    version: ">=4.6.0"
  - name: infra.controller_configuration
    version: ">=3.0.0"
  - name: awx.awx
    version: ">=24.0.0"
  - name: community.general
    version: ">=9.0.0"
