apiVersion: v1
kind: Namespace
metadata:
  name: iso-platform
  labels:
    app.kubernetes.io/part-of: iso-compliance-platform
    pod-security.kubernetes.io/enforce: baseline
    openshift.io/cluster-monitoring: "false"
    openshift.io/user-monitoring: "true"
    opendatahub.io/dashboard: "true"
    opendatahub.io/project-type: default
    opendatahub.io/managed: "true"
