apiVersion: v1
kind: Namespace
metadata:
  name: openshift-jobset-operator
  labels:
    app.kubernetes.io/part-of: iso-compliance-platform
    app.kubernetes.io/component: jobset
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: JobSet Operator
