apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - minio.yaml
  - connections.yaml
  - dspa.yaml
  - ogxserver.yaml
  - mlflow.yaml
  - evalhub.yaml
  - feast.yaml
  - workbench.yaml
  - localqueue.yaml
  - mcpserver.yaml
  - seed-autorag.yaml
