apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iso-platform
resources:
  - iso-api.yaml
  - iso-web.yaml
  - iso-docgen.yaml
  - playground.yaml
  - playground-redirect.yaml

images:
  - name: iso-api
    newName: image-registry.openshift-image-registry.svc:5000/iso-platform/iso-api
    newTag: latest
  - name: iso-web
    newName: image-registry.openshift-image-registry.svc:5000/iso-platform/iso-web
    newTag: latest
  - name: iso-docgen
    newName: image-registry.openshift-image-registry.svc:5000/iso-platform/iso-docgen
    newTag: latest
