apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: playground
  labels:
    app.kubernetes.io/name: playground
    app.kubernetes.io/component: playground-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: playground
  namespaceSelector:
    matchNames:
      - iso-platform
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
