apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: iso-api
  labels:
    app.kubernetes.io/part-of: iso-compliance-platform
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: iso-web
  labels:
    app.kubernetes.io/part-of: iso-compliance-platform
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: iso-docgen
  labels:
    app.kubernetes.io/part-of: iso-compliance-platform
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rag-iso
  labels:
    app.kubernetes.io/part-of: iso-compliance-platform
