FROM registry.access.redhat.com/ubi9/nodejs-20:latest AS build
USER 0
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npm run build

FROM registry.access.redhat.com/ubi9/nginx-126:latest
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
USER 1001
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
