apiVersion: v1
kind: Namespace
metadata:
  name: openshift-kueue-operator
  labels:
    app.kubernetes.io/part-of: iso-compliance-platform
    app.kubernetes.io/component: kueue
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: Red Hat build of Kueue
