apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iso-01-platform-infra
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: iso-compliance-platform
spec:
  project: default
  source:
    repoURL: https://github.com/ypreiger/iso-compliance-platform.git
    targetRevision: main
    path: gitops/layers/01-platform-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: iso-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
