apiVersion: v1
kind: Namespace
metadata:
  name: openshift-tempo-operator
  labels:
    app.kubernetes.io/part-of: iso-compliance-platform
    app.kubernetes.io/component: observability
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: Tempo Operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: tempo-product
  namespace: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tempo-product
  namespace: openshift-tempo-operator
  labels:
    app.kubernetes.io/part-of: iso-compliance-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: tempo-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
