apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-labels.yaml
  - trustyai-service.yaml
  - guardrails-orchestrator.yaml
  - rbac.yaml
  - model-aliases.yaml
  - whisper-maas.yaml
  - maas-lab-whisper-dashboard.yaml
  - bge-m3-simple.yaml
  - bge-m3-external-model.yaml
  - gpt-oss-20b.yaml
  - llm-servicemonitors.yaml
  - llm-grafana-dashboard.yaml
