apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iso-rag-data
  labels:
    app.kubernetes.io/component: rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
