apiVersion: v1
kind: Pod
metadata:
  name: privileged-demo
  namespace: demo-app
  labels:
    app: privileged-demo
spec:
  containers:
    - name: pause
      image: registry.access.redhat.com/ubi9/pause:latest
      securityContext:
        privileged: true
  restartPolicy: Never
